// Black Ledger - vehicle/boss biography data (auto-generated from
// docs/DesignBible_v0.3.docx by tools/gen_vehicle_bios.py - do not hand-edit).
// Backstory + Intro storyboard per contestant; the Intro text is the
// placeholder shown on "Watch Intro" until the real motion-comics exist.
#pragma once
#include "CoreMinimal.h"

struct FBLVehicleBio
{
	const TCHAR* Key;          // matches save unlock names / asset folder
	const TCHAR* Number;       // roster index label
	const TCHAR* DisplayName;
	const TCHAR* Tagline;
	const TCHAR* Bio;
	const TCHAR* Intro;     // ~30s intro storyboard (motion-comic beats)
	const TCHAR* Ending;    // ~60-90s ending storyboard
	bool bBoss;
};

// --- launch roster (16), in roster order ---
static const FBLVehicleBio GBLLaunchBios[] =
{
	{
		TEXT("Surgeon"), TEXT("01"), TEXT("THE SURGEON"),
		TEXT("I can save her. I have to be allowed to save her."),
		TEXT("Dr. Eli Vance was the kind of surgeon other surgeons quoted. Sixteen years at Mercy General, hundreds of saves, the kind of steady hands that don't tremble even on hour eleven. He had a daughter, Cora, age four, with a congenital heart defect. He told his wife he could fix it himself. He told the hospital board he could fix it himself. He could not fix it himself.\n\nCora died on his table at 11:47 PM on a Tuesday. The malpractice case was dismissed  -  there was no malpractice, only the unbearable arithmetic of a defect too complex for any surgeon, including her father. His wife left him. His license followed two years later, after the drinking and the failed reinstatement of three other patients he was no longer steady enough to save.\n\nHe lives in his car now. The ambulance was bought at auction. He converted it himself. He believes  -  has to believe  -  that if he wins, the Auditor will give him back the eleven minutes between 11:36 and 11:47 PM. He has rehearsed those eleven minutes for nine years."),
		TEXT("Open on a still shot of an empty operating theater, dim. The Surgeon stands in scrubs, washing his hands. The water runs red. He doesn't react. Cut to the ambulance idling in rain outside a closed hospital. He steps in, places a child's stuffed rabbit on the dashboard, and adjusts it with surgical care. Voiceover (his own voice, addressing himself): 'You will not shake. You will not blink. You will save her this time.' The ambulance pulls away. Title card: THE SURGEON."),
		TEXT("He wins. The Auditor sits across from him in the operating theater, now restored to pristine white. The Auditor says: 'The entry has been struck.' The Surgeon looks at his hands; they are steady. He understands. He drives home. The house is bright, warm. His wife is there. She doesn't recognize him  -  she is younger, happier, married to someone else who is not him. From the kitchen, a little girl runs out. 'Daddy!' she calls, and she runs past the Surgeon to the man behind him. The Surgeon was never her father. The defect was never his to fix. He saved her by never existing in her life. The camera holds on his face for ten silent seconds. Cut to black."),
		false
	},
	{
		TEXT("Antoinette"), TEXT("02"), TEXT("MISS ANTOINETTE"),
		TEXT("They called me the most beautiful woman in three states. Past tense is unkind."),
		TEXT("Adeline Marchetti won Miss Tennessee in 1973. She won Miss Mid-South in 1974, 1975, and 1976. She was on the cover of three magazines and dated a senator's son. She believed, with the full conviction of someone who had never been told otherwise, that her face was her contract with the world.\n\nThe contract expired. She tried to renew it  -  surgeries, treatments, increasingly experimental therapies from doctors who shouldn't have had licenses. The results were temporary, then ruinous. By the time she was sixty, she had spent her inheritance and her face had been rebuilt three times. Now she lives in a closed-off wing of her family home, the mirrors covered. She has not been photographed in fifteen years.\n\nThe Auditor's letter arrived in a pink envelope. She believes  -  wants to believe  -  that he will undo it. All of it. Give her back the face the world owed her."),
		TEXT("Open in a darkened bedroom. A figure sits at a vanity, back to camera. We see only her hands  -  slender, with manicured nails, but the skin is loose, age-spotted. She reaches up and slowly removes a velvet cloth from the mirror. We see her reflection only as a blur of light  -  the camera refuses to focus on her face. She smiles. We see the smile in shadow. 'It's time, darling. One last show.' She rises, dressed in immaculate pink. The Cadillac waits. Title card: MISS ANTOINETTE."),
		TEXT("She wins. The Auditor presents her with a single hand mirror, ornate and silver. 'The entry has been struck.' She looks in. She is twenty-three again  -  flawless, radiant, the face she wore on magazine covers. She weeps with joy. She races home. She unveils every mirror in the house. In every mirror, she is twenty-three. But she catches her reflection in a window pane that night and sees the truth: she is still seventy-one. The mirrors are lying. Anyone who looks at her sees youth  -  she alone sees age. The Auditor erased her entry in the world's perception, but he could not erase her from her own. She lives the rest of her life unable to be alone with her own reflection. She covers every reflective surface in her house. She lasts six months before she shatters every mirror she owns. The final shot is her sitting in the dark, surrounded by broken glass, finally smiling. The shards on the floor show a young woman, smiling back."),
		false
	},
	{
		TEXT("Hollow"), TEXT("03"), TEXT("HOLLOW"),
		TEXT("The fire said it was hungry. I only fed it."),
		TEXT("Nobody knows his name. He has been picked up by police in six states over fourteen years; each time, his fingerprints don't match any database. His face  -  when he removes the mask  -  has burn scars that obscure his features. He wears a faded firefighter's mask repurposed as a hood, the visor cracked.\n\nHe doesn't remember why he burns things. He only remembers that he must. The compulsion is not malicious in his mind  -  it is owed. Something is owed to fire. He has theories that come to him in dreams: a house, a stairwell, two small voices calling for him. He doesn't know if he was trying to save them or if he started the fire.\n\nHe wants to remember. The Auditor's offer is the first thing in fourteen years that has felt like it might give him an answer."),
		TEXT("Open on a burning building at night. Hollow stands in the street watching it, fire reflected in his cracked visor. A child's bicycle lies in the yard, untouched. He stares at it. A tear runs down his cheek  -  but he is smiling under the mask. He turns away, climbs into Pyre, and drives off. Title card: HOLLOW."),
		TEXT("He wins. The Auditor takes him to a suburban street he doesn't recognize but his hands shake walking it. They stop in front of a two-story house. The Auditor opens the front door. Hollow walks in. He remembers. He set the fire  -  but only to make the insurance pay, to save his family from foreclosure. He didn't know they hadn't gotten out. The two voices were his daughters. He stayed long enough to drag them from the smoke but they did not survive the burns. He has spent fourteen years lighting fires looking for the moment he could have run faster. The Auditor stands in the doorway. 'The entry has been struck.' Hollow looks down. His hands are unburned. He is a young man again. He hears, very faintly, two little girls laughing from upstairs. He starts toward the stairs. The Auditor closes the door behind him. We never see what is upstairs. The screen holds black for a long beat. Then, very softly: the sound of fire."),
		false
	},
	{
		TEXT("Warden"), TEXT("04"), TEXT("THE WARDEN"),
		TEXT("He told me he was innocent. I had heard that every day for twenty years."),
		TEXT("Captain Marcus Reilly worked Ridgemont for thirty-one years. He was respected, feared, and famously incorruptible. He had a phrase he used with new guards: 'Every man here says he's innocent. Treat them all the same.'\n\nIn 2009, inmate Daniel Voss told him he was innocent. Voss was scheduled for transfer to general population that week from solitary. Voss told Reilly that a man in general would kill him on day one over an old debt. Voss begged. Reilly transferred him on schedule. Voss was dead within nine hours.\n\nThree years later, DNA evidence cleared Voss of the original crime. He had, in fact, been innocent. Reilly resigned within the month. He has spent the years since reading every word of Voss's case file, again and again. He keeps a photograph of Voss on the dashboard of the van. He believes if he wins, he can transfer Voss back to solitary. He can keep him alive. He can be the man who listened."),
		TEXT("Open in a prison visitor's room, empty. The Warden sits across from an empty chair, hands folded. He speaks to no one. 'I should have listened.' Cut to him in uniform packing a locker  -  the badge goes in a box; the photograph of Voss goes in his pocket. Cut to him climbing into the Cage in the present, the photograph going onto the dashboard. He starts the engine. Title card: THE WARDEN."),
		TEXT("He wins. The Auditor stands in the empty cellblock at Ridgemont. 'The entry has been struck.' The Warden walks to Voss's old cell. The door is open. Voss is inside, alive, healthy, exactly as he was the day before the transfer. Voss looks up. 'You came back.' The Warden steps in. The door closes behind him automatically. Voss stands up  -  and walks out of the cell. The door doesn't open for the Warden. He is in the cell now. He will serve Voss's sentence, in his place. From outside, Voss looks at him with no emotion. 'Every man in here says he's innocent.' The Auditor's voice, distant: 'The entry has been struck.' The Warden was the entry. He gave the years he owed."),
		false
	},
	{
		TEXT("Pup"), TEXT("05"), TEXT("PUP"),
		TEXT("Pup just wants to go home. Pup doesn't want to be alone anymore."),
		TEXT("Pup is not the child's name. Pup doesn't remember the child's name. Pup remembers a backyard, a swing set, a mother calling for dinner, and then the ice cream truck  -  and then the truck and Pup were one thing, and the backyard was a long time ago.\n\nThe game leaves Pup's nature deliberately ambiguous. Possible interpretations: a child who was killed in 1987 by an ice cream truck driver and whose ghost merged with the vehicle; a creature that has always existed wearing a child's appearance to lure victims; a manifestation of the Auditor's office itself. Pup's dialogue supports all three.\n\nPup wants to 'go home,' but home isn't a place. Home, in Pup's vocabulary, is a moment  -  the moment before something happened. Pup cannot describe the something."),
		TEXT("Open on a residential street in summer daylight  -  but the colors are oversaturated, almost wrong. The ice cream truck rolls slowly past empty houses. The jingle plays. We see Pup through the serving window: a child in a yellow t-shirt and shorts, face in shadow. A single child's drawing flutters from the truck and lands on the road behind it. We see the drawing: a stick figure family of three under a black scribble that might be a cloud. Title card: PUP."),
		TEXT("Pup wins. The Auditor stands in a backyard with a swing set. Late afternoon, golden light. 'The entry has been struck.' Pup climbs onto the swing. A woman's voice from offscreen: 'Pup! Honey, dinner!' Pup smiles  -  we see Pup's face for the first time, and it is a perfectly normal eight-year-old boy. Pup runs toward the house. Cut to black. Then: the ice cream truck, abandoned by the curb in front of the now-empty house. The jingle is still playing. Slowly, the driver's-side door opens. Something we don't see climbs out. The jingle stops. We hear, very faintly, a child's voice from inside the truck saying, 'It's your turn now.' Cut to black. (Implication left ambiguous: did Pup go home, or did Pup escape and pass the curse to someone else? Player chooses what to believe.)"),
		false
	},
	{
		TEXT("Crucible"), TEXT("06"), TEXT("CRUCIBLE"),
		TEXT("I was the foreman. They were my men. I gave the order to stay."),
		TEXT("Anton 'Tony' Bessemer worked Crucible Steel in Ashen Hollow for twenty-eight years, the last six as shift foreman. On October 14, 2003, a structural support in Furnace Three failed during a pour. Tony saw the warning signs four minutes before the collapse. He gave the order for his men to finish the pour before evacuating  -  a decision driven by quotas and the conviction that the support would hold for another thirty seconds.\n\nIt did not. Eleven men died. Tony was outside the structure when it came down, having gone to retrieve a safety officer. He lived. The investigation found him technically not at fault  -  the support's failure was structural, predating his shift  -  but he knew what he had said. He had said: 'Finish the pour.' He had been afraid of falling behind.\n\nTony has driven a scrap hauler in Ashen Hollow for the twenty-three years since. He drinks at the same bar every night. He has never spoken about that day, including to his wife, who left him in 2008. The Auditor's letter is the first thing he has wanted to win in two decades."),
		TEXT("Open inside a steel mill, daytime, decades ago. Tony in foreman's gear stands on a catwalk watching a pour. We see his men below, working. He hears a creak. He looks up. He looks at his clipboard. He hesitates. Cut to present-day Tony in the same mill, now ruined, standing in the same spot. He has tools in his hands but isn't working. He just stands there. He hears the same creak, in memory. He climbs down to Bessemer and starts the engine. Title card: CRUCIBLE."),
		TEXT("Crucible wins. The Auditor stands with him on the catwalk, October 14, 2003. 'The entry has been struck.' Tony watches himself, four minutes before the collapse, give the order to evacuate. The men get out. The furnace collapses on empty floor. His men live. He drives home that night to his wife. She is happy. He is a hero in the union hall the next week. Cut to: six months later, in a different city. A different furnace. The same structural defect, in a different mill. A different foreman makes a different call. Twelve men die. Cut to: a year after that, a different mill, a different collapse, a different toll. The Auditor's voiceover, calm: 'The entry was struck from your ledger. It had to be filed somewhere else.' Tony lives the rest of his life as a hero in Ashen Hollow, reading newspapers about disasters that follow him from a distance, knowing  -  knowing  -  that he traded his own guilt for theirs. He visits a different cemetery every year on October 14th. There is always a fresh one to visit."),
		false
	},
	{
		TEXT("Cartographer"), TEXT("07"), TEXT("THE CARTOGRAPHER"),
		TEXT("There is a place I have dreamed of since I was a girl. It is not on any map. So I am making one."),
		TEXT("Dr. Eleanor Vance (no relation to the Surgeon) is a respected geographer who, in 2019, began publishing increasingly strange papers about a place she called 'the Quiet Coast.' Her colleagues assumed it was a metaphor  -  a kind of personal Atlantis used to illustrate the cartographic urge. It wasn't. She had been dreaming of it since age six: a coastline of dark water, a single lighthouse, a town in the distance that she had never reached.\n\nIn 2022 she took leave from the university and began driving. She has covered 180,000 miles in three years searching for the coastline. She has narrowed it down to three possible locations. She has stopped calling her sister. She has stopped sleeping much.\n\nThe Auditor's letter contained, instead of an invitation, a partial map  -  and the partial map matched her notes. She believes the Auditor can complete it. She does not know that completing it is precisely the wrong thing to want."),
		TEXT("Open in a cluttered office, walls covered in maps. Eleanor stands at a chalkboard drawing a coastline from memory. She has drawn this coastline a thousand times. She closes her eyes. We see, in her mind: dark water, a lighthouse, a town in the distance. The dream pulls away as we hear a knock on her door. The letter slides under it. She opens it. The Auditor's partial map. Her hand trembles. She gathers her keys. Title card: THE CARTOGRAPHER."),
		TEXT("She wins. The Auditor presents her with the completed map. The Quiet Coast is a real place  -  specific coordinates in northern Maine. She drives there immediately. She walks the beach. It is exactly as she dreamed: the dark water, the lighthouse, the town. She is overwhelmed with relief. She walks toward the town. As she approaches, she begins to recognize details  -  the streets, the houses, a small graveyard at the town's edge. She walks to the graveyard. There is one fresh grave. The headstone bears her own name and a date  -  today's. She turns to leave. She cannot. The town's edge is now miles behind her. The lighthouse is closer. The water is rising. The Auditor's voiceover: 'You sought it. It sought you. The entry has been struck.' She has spent her whole life trying to reach the place where she will die. Now she has. She has nowhere else to go."),
		false
	},
	{
		TEXT("Lien"), TEXT("08"), TEXT("THE LIEN"),
		TEXT("Everything in this town has a price and a due date. I just collect."),
		TEXT("Silas Crane never broke a law. He read them. When the mill closed and Ashen Hollow's property values cratered, Crane bought the distressed paper  -  mortgages, medical debt, title loans  -  for cents on the dollar, then collected at full face value with interest, fees, and the full violence of the courts behind him. He was the best in three counties. He kept a ledger of his own, leather-bound, a detail the Auditor noted with something like professional courtesy.\n\nThe entry that unbalanced him: the Ardetti family. A widow, two children, a reverse-mortgage trap on the house her late husband signed without reading. Crane foreclosed in February. He had the sheriff set their belongings on the curb in eleven-degree cold, because the eviction order said 'forthwith' and forthwith was efficient. The widow, Donna Ardetti, did not go to a shelter. She went back into the emptied house that night, sealed the kitchen, and ran the car. The older child got out. The younger did not.\n\nCrane attended neither funeral. He did, however, keep the file. He reads it the way the Warden reads Voss's. He wants the Auditor to strike the day he bought the Ardetti paper. He tells himself it's mercy. It is the first merciful thought he has ever had, and he doesn't trust it."),
		TEXT("Open in a wood-paneled office, after hours, a green banker's lamp. Crane signs a stack of foreclosure orders without reading them  -  stamp, stamp, stamp. He pauses at one file: ARDETTI. He doesn't open it. He sets it face down and keeps stamping. Cut to him in the lot, climbing into the tow truck; the wedding rings on the windshield chain catch the streetlight. He starts the engine and the whole rig groans under its cargo. Title card: THE LIEN."),
		TEXT("He wins. The Auditor hands him a single sheet  -  the Ardetti note, the day he bought it. 'The entry has been struck.' Crane is back in his office that morning, the distressed-paper portfolio open. He crosses the Ardetti loan off the buy list. He does the merciful thing. He never owns the house; he never forecloses; Donna Ardetti and both children live. Crane feels, for the first time in his life, clean. He retires. He gives money away. He dies old, in a bed, forgiven by a town that never knew his name. Cut to: the house. Because Crane didn't buy the note, someone else did  -  a collections outfit with no courtroom patience and no ledger at all. They didn't wait for forthwith. The way they cleared the house was faster, and worse, and the widow and both children  -  both, this time  -  were home when it happened. The Auditor, quietly: 'Someone always holds the paper. You were, it turns out, the gentlest hand it could have fallen into.' Crane's peaceful death plays again, and we understand he never knew. He spent his whole forgiven life clean of a kindness that killed more than his cruelty ever had. The Ledger balanced. It just balanced somewhere he couldn't see. Cut to black."),
		false
	},
	{
		TEXT("Hemlock"), TEXT("09"), TEXT("HEMLOCK"),
		TEXT("The river remembers every drop they poured into it. So do I."),
		TEXT("Dr. Maren Vale was a hydrologist with the state environmental agency. She discovered that the chemical reprocessor that bought Crucible Steel's dead land had been injecting solvent waste into the aquifer beneath Ashen Hollow for years  -  contamination that tracked, street for street, onto a childhood-leukemia cluster in the low wards. She filed reports. They were buried. She was reassigned, then discredited, then fired; a settlement she never signed appeared bearing her forged signature.\n\nAfter three years of legal dead-ends, she stopped trusting paper. She joined  -  then led  -  a cell that sabotaged the plant's pumps and pipelines until the spills became impossible to hide and the federal regulators were forced in. The campaign worked. But her last action  -  breaching a containment tank to flood the site with its own evidence before it could be scrubbed  -  released a plume into the storm drains faster than she had modeled. A maintenance crew was working a line downstream: three men, one of them barely twenty. Two lived. The youngest, Theo, drowned in chemical runoff in a culvert in the dark. She had checked the work schedule. She had the wrong week.\n\nShe has lived off-grid since, driving the stolen district tanker  -  once used to flush the very mains she sabotaged  -  full of the river's poisoned water as evidence she can no longer deliver to anyone. She believes that if she wins, the Auditor will let her unsend the team into that culvert. Give the youngest back the week."),
		TEXT("Open on a culvert mouth at dawn, water the color of motor oil sliding out of it. Maren stands at the lip in waders, holding a sample vial up to the gray light; the liquid inside is the same color as the water. She doesn't collect it. She just looks. Cut to her climbing into the tanker; she touches the small hard hat on the mirror, once, the way someone touches a photograph. The engine turns over wet and reluctant. The tank behind her sloshes. Title card: HEMLOCK."),
		TEXT("She wins. The Auditor meets her on the bank of the Ash River, clean now, silver in the sun  -  the way it must have looked a century ago. 'The entry has been struck.' She understands at once: the breach never happened. She is back in the third year, across a desk from a federal attorney who finally, finally believes her. No one sabotages anything. The case goes the right way  -  slowly. The plant fights it in court for nine years: injunctions, appeals, continued legal permitted discharge 'pending review.' Maren, vindicated and useless, watches the leukemia cluster widen ward by ward from her seat in the gallery. The boy Theo lives  -  grows up two streets from the plant, drinks the water every day of the childhood she preserved, and is diagnosed at nineteen. Her one act of violence, struck from the Ledger, had been the only thing that ever made them stop in time. The Auditor, gently: 'You wished to take the water back. I have. Every drop. It had to go somewhere.' Final shot: Maren, older, alone, at the same culvert  -  but now it runs clear, and that is so much worse. She has nothing left to carry, and nothing left to prove. The river is clean and the children are still sick and no one will ever know why. Cut to black."),
		false
	},
	{
		TEXT("Shepherd"), TEXT("10"), TEXT("THE SHEPHERD"),
		TEXT("I counted forty souls onto that bus. The Lord only asked me for thirty-nine."),
		TEXT("Brother Amos Teel preached on a county road outside Ashen Hollow for thirty years  -  a small, sincere, increasingly fervent congregation he called the Hollow Light. He was not a con man. That is the tragedy. He believed. When the mill closed and the town began to die, his sermons turned apocalyptic, and his people, who had nothing else, believed with him.\n\nIn the winter of the worst year, Teel announced a 'deliverance': he had been told, he was certain, to lead the faithful out of the dying valley in a single bus, on a single night, to high ground before a judgment that was coming. Forty people boarded. He drove them through a blizzard up the Switchback toward the reservoir, singing. The road was closed for a reason. The bus went through the guardrail and into the spillway. Teel was thrown clear into a snowbank. He was the only one. Thirty-nine drowned or froze in a county bus in the dark, singing, because he told them God said go.\n\nThe investigation called it the act of a deluded man; the survivors' families called it murder; Teel calls it obedience, and obedience is the only thing keeping him from understanding what he did. He wants the Auditor to give him back the moment at the wheel. He does not want his own life back. He wants theirs."),
		TEXT("Open inside the bus, in memory  -  warm light, forty faces, everyone singing 'Shall We Gather at the River.' Teel at the wheel, radiant, weeping with joy. He turns to look at his flock. He takes his eyes off the road. Snow fills the windshield. Cut to present: the bus on a frozen lot, dark, empty, Teel alone in the driver's seat in the cold. He can still hear the hymn, faintly. He grips the wheel. Title card: THE SHEPHERD."),
		TEXT("He wins. The Auditor sits in the front pew of a small country church. 'The entry has been struck.' Teel is back at the wheel on the night of the deliverance  -  and this time God is silent. No call comes. He doesn't start the bus. The forty go home to their cold houses. And nothing changes, because the judgment he preached was never real, and without it the Hollow Light is just forty frightened, broke people in a dying town. Over the next five winters, with no deliverance to wait for and no faith to hold them, they scatter or sicken or give up. Teel buries thirty-nine of them  -  the same thirty-nine  -  one at a time, of despair and cold and the ordinary apocalypse of a place the world abandoned. At the last funeral, the Auditor stands at the back of the church. 'You asked Me to take the night back. I did. The river was always going to have them. I only granted you the time to learn each of their names as you put them in the ground.' Teel, alone in the empty church, finally stops being able to call it obedience. The hymn plays out over black  -  forty voices, then thirty-nine, then one, then none."),
		false
	},
	{
		TEXT("Specter"), TEXT("11"), TEXT("SPECTER"),
		TEXT("I had eyes on for nineteen days. I knew his kids' names. Command called it a clean strike."),
		TEXT("Staff Sergeant Dana Reyes flew nothing. She sat in an air-conditioned trailer in the high desert, eight thousand miles from the war, and watched men through a camera that could read a license plate from two miles up. For nineteen days she watched one compound, one man  -  a 'high-value individual.' She watched him eat, pray, carry his daughter on his shoulders, fix a motorbike. She built the pattern of life that would kill him.\n\nOn the twentieth day, command gave the order during the window the analysts liked. She lased the target; another operator pulled the trigger; the missile took eleven seconds to fall. In second nine, the children ran into the courtyard. She called the abort. Eleven seconds is not enough time. The after-action review found the strike 'lawful and proportionate.' Eighteen months later the intelligence that named him a high-value target was quietly retracted. He had been a man who fixed motorbikes.\n\nReyes kept the freeze-frame from second nine. She wants the Auditor to give her back those eleven seconds  -  to make the missile fall on empty ground."),
		TEXT("Open on grayscale drone-camera footage  -  a courtyard from above, a man, two small shapes, the crosshair drifting over them, a timer ticking in the corner. We hear Reyes's voice, flat: 'Good tone. Target acquired.' Then, half a beat too human: '...standby  -  standby, I have children in the  -  abort, abort  - ' The footage whites out. Cut to present: Reyes in the dark interior of the control truck, the same frozen frame on the center monitor, her face lit gray. She reaches up and taps the screen, once. The engine starts somewhere behind her. Title card: SPECTER."),
		TEXT("She wins. The Auditor's voice comes over her headset, not the radio: 'The entry has been struck.' She is back in the trailer, second nine, and this time the abort lands  -  the other operator steers the missile wide; it falls on empty ground; the man and his daughter live. The official record shows no strike, no casualties, a clean stand-down. Reyes is discharged with a clear conscience and a commendation. She builds the life she'd written off: a husband, a house with a yard, a daughter of her own. And it is fine, for a while. Then: a summer afternoon, her daughter on a swing-set, the long shadow of the swing crossing the dirt at exactly the angle of that courtyard at midday. Reyes is at the kitchen window watching her child the way she once watched a stranger for nineteen days  -  and she understands that the Auditor struck the strike from the world but not from her. She still built the pattern of a man's life in order to end it. She still watched the children run in. The missile still falls, every time she closes her eyes, on the only courtyard that was ever really hers. The record is clean. She is not. The Auditor: 'I struck the entry. I could not strike the operator. You were never on the page. You were the one reading it.' Final shot: the grayscale crosshair, drifting over a child on a swing  -  in color now, in her own backyard. Cut to black."),
		false
	},
	{
		TEXT("Refuse"), TEXT("12"), TEXT("REFUSE"),
		TEXT("Truck's loud. Hydraulics are louder. You learn not to listen close. That was the whole job."),
		TEXT("Gil Mott ran Route 7 for twenty-six years. Same streets, same cans, same dark winter mornings doing a job the city only notices when it stops. He was good at it the way you're good at anything you've stopped having to think about.\n\nOn a sub-zero morning in January, working alone and ahead of schedule, he tipped a commercial dumpster behind the shuttered bus depot into the hopper and ran the compactor, the same as ten thousand times before. There had been a sound  -  a soft one, under the hydraulics. He told himself it was a cat. He had told himself it was a cat about a sound every few weeks for years, and it had always been a cat or a bag or nothing. It was not a cat. A runaway, sixteen years old, named Wren, who had been sleeping in the depot dumpsters for warmth, was inside. They found out three days later.\n\nThe inquest cleared Gil completely: no way to see, no way to know, a tragedy, not a crime. Everyone agreed. Gil agreed, out loud. But he had heard the sound, and he had not stopped, because stopping was not the job and the job was the only thing that had ever asked nothing of him. He wants the Auditor to give him back the half-second when he heard it  -  to let him stop the cycle and look."),
		TEXT("Open before dawn, snow, the truck's amber light turning. Gil works alone, breath fogging, the rhythm of the route  -  grab, tip, cycle, drive on. He tips a dumpster. He thumbs the compactor. Under the hydraulics, very faint: a sound. He pauses  -  half a second  -  hand on the lever. Then he runs the cycle and climbs back in and drives on, because that's the job. The amber light pulls away down the empty street. Title card: REFUSE."),
		TEXT("He wins. The Auditor stands with him behind the bus depot, that morning, snow falling. 'The entry has been struck.' Gil hears the sound again  -  and this time he stops the cycle. He climbs down. He looks. He finds her, half-frozen and terrified but alive, and he pulls her out and wraps her in his coat and calls it in, and a sixteen-year-old goes home. Gil is, briefly, a hero  -  the garbageman who saved a kid. And then the ending does the cruelest thing it can: it shows you the next morning, and the next. Gil can't stop hearing the sound now. Every dumpster. Every cycle. He stops the compactor to check, every time, on every can, because he heard it once and he was right. The route that took four hours takes nine. He's reassigned, then written up, then let go  -  a man who can't do the only job he ever had because he can't stop listening for the kid who isn't there anymore. He saved her by becoming a man who hears her in everything. The girl he rescued grows up and never thinks of him again, which is exactly right, which is the whole point. The Auditor: 'You wished to hear the sound in time. You will hear it in time forever now.' Final shot: Gil, years later, in the dark cab of a truck he is no longer allowed to drive, behind the depot, listening. Cut to black."),
		false
	},
	{
		TEXT("Bride"), TEXT("13"), TEXT("THE BRIDE"),
		TEXT("I was nine words from married. He never heard the other nine."),
		TEXT("Imogen Ash got as far as 'I, Imogen, take thee - .' Her groom, Daniel, was twelve feet away at the front of St. Dymphna's chapel when the chandelier  -  original to the 1890s building, condemned along with the rest of the parish, hung anyway because Imogen wanted that church  -  came down. It killed him and the priest and missed Imogen by the length of a veil. She finished the sentence to a dead man because her mouth didn't know how to stop. She was twenty-nine.\n\nShe has worn the dress every day for twenty-three years. Not the same dress  -  she has it remade, identically, as it rots; there is a seamstress in the Tenements who has sewn the same gown eleven times and asks no questions. She kept the limousine too, the one meant to drive them away under a hail of rice. She lives in it as much as in the house.\n\nShe has rewritten the wedding ten thousand times in her head: a different church, a later date, a sentence finished. She wants the Auditor to let her finish it. To get to 'and.'"),
		TEXT("Open inside the chapel, the morning of, golden light through stained glass, Imogen at the altar mid-vow, radiant, looking at someone we don't see. 'I, Imogen, take thee - ' A creak above. Her smile doesn't move. Cut to black on the creak. Present: the limousine idling outside the same chapel, now condemned and dark; Imogen in the driver's seat in her gown, veil down, fresh bouquet on the dash. She lifts the veil and smiles at the rearview mirror as though at a congregation. 'Don't be nervous. Everyone's watching.' She pulls away, cans clattering. Title card: THE BRIDE."),
		TEXT("She wins. The Auditor waits at the altar in place of the priest. 'The entry has been struck.' Imogen is twenty-nine again, mid-vow, golden light  -  and this time there is no creak. She finishes the sentence: '...to be my husband.' Daniel says his. They marry. The rice falls. The limousine carries them away and she gets the and  -  the honeymoon, the first apartment, the ordinary years. And the ending lets her have all of it, in a warm montage that is almost merciful: a real marriage. Which means the small fights, the dull stretch in year six, the way he chewed, the affair that didn't happen but could have, the slow discovery that Daniel was a perfectly ordinary man and not the perfect husband she had spent twenty-three years building out of twelve feet and one word. She does not stop loving him. But she learns him, all the way, the way you can only learn someone you don't lose at the altar  -  and in learning him she loses the radiant, deathless, twelve-foot Daniel she had instead. He dies anyway, decades on, of something ordinary, an old man in a hospital, and she is an old woman at the bed, and it is sad the way all long marriages end and not transcendent at all. The Auditor, at the funeral: 'You wished to finish the sentence. You did. I cannot give you a perfect husband and a real one both. You had the perfect one for twenty-three years. You traded him for the man.' Final shot: old Imogen in ordinary widow's black for the first time in her life  -  the white dress gone  -  sitting alone, and we cannot tell whether her face holds grief or relief, and neither can she. Cut to black."),
		false
	},
	{
		TEXT("Hunter"), TEXT("14"), TEXT("THE HUNTER"),
		TEXT("Opening morning. Gray light. Something moved in the brush where the deer come through. I'd been hunting forty years. I didn't miss."),
		TEXT("Caleb Roe taught his son Danny to hunt the way his own father taught him: patience, respect, one clean shot, never fire at what you haven't identified. Danny was nineteen, home from his first year of college a different person  -  quieter, taller, wearing a tan jacket Caleb didn't recognize instead of the blaze orange Caleb had bought him every year since he was eight.\n\nOpening morning, the two of them split to walk a draw from both ends and meet in the middle, the way they had a hundred times. Caleb reached the meeting spot first. Something moved in the brush where the deer always came through  -  low and tan and fast in the gray half-light. Forty years of instinct, and one cardinal rule he had recited ten thousand times  -  be sure of your target  -  and the instinct won by the quarter-second it takes to break a life. He did not miss. He never missed.\n\nHe has not picked up a rifle since, except the one mounted in the truck, which he cannot bring himself to fire and cannot bring himself to sell. He wants the Auditor to give him back the quarter-second. To make himself wait. To make himself sure."),
		TEXT("Open in gray pre-dawn woods, frost, breath. Caleb walks a draw, rifle low, calm, in his element  -  the one place he was ever fully himself. He reaches a clearing. Across it, brush moves  -  low, tan, quick. He raises the rifle in one smooth forty-year motion. The reticle settles. His finger takes up the slack. We do not see the far side. We hear the shot, and then nothing  -  no animal sound, just the woods going quiet the way they do after. His face changes. Cut. Present: Caleb in the truck cab at the trailhead, dawn, the unfired rifle in the rack behind his head, Danny's orange cap swinging from the mirror. He starts the engine. Title card: THE HUNTER."),
		TEXT("He wins. The Auditor stands with him in the gray clearing, opening morning. 'The entry has been struck.' The brush moves. And this time Caleb waits. He holds the cardinal rule. He calls out  -  'Danny?'  -  and his son's voice comes back, annoyed and alive, 'Dad, it's me, don't shoot,' and steps out of the brush in that tan jacket, nineteen and whole. Caleb lowers the rifle with hands that won't stop shaking, and they walk out of the woods together, and Danny goes back to school and lives. Here the ending is almost kind  -  there is no widening disaster, just the quiet true thing the others learn the hard way. Because Caleb still raised the rifle. He waited the quarter-second this time, but he knows, and worse, the boy knows, that his father's first instinct on seeing movement where his son stood was to fire. That knowledge sits at every dinner for the rest of their lives. Danny is careful around him in a way he never used to be. He stops coming home for opening day. He stops coming home. He is alive in another city, with children Caleb sees only in photographs, and Caleb got exactly what he asked for  -  the boy, breathing  -  and lost the one thing the bullet had left him, which was a son who didn't know. The Auditor: 'You asked to be sure of your target. Now you are. So is he.' Final shot: Caleb alone at the trailhead at first light, an old man, the orange cap still on the mirror, the rifle still unfired, the passenger seat empty in a different way than before. He doesn't start the engine. Cut to black."),
		false
	},
	{
		TEXT("Photographer"), TEXT("15"), TEXT("THE PHOTOGRAPHER"),
		TEXT("The light was perfect. That's the part no one forgives. The light was perfect and I took it."),
		TEXT("Mona Vane built a career on being there  -  first to the wreck, the fire, the flood, camera up while everyone else's hands were busy. The photograph that made her name and ended her: a famine assignment, a collapsed child, a long lens, and a choice she made in a quarter-second that she has defended in interviews and never once believed. She framed. She focused. She waited for the light. She shot. And then  -  she says  -  she helped; but the child was gone and the frame was perfect, and the frame is what survived.\n\nIt won everything. She has spent the years since unable to look at it and unable to stop looking at it. She drinks. She left the country, then the work, then the world.\n\nShe wants the Auditor to let her put the camera down in that quarter-second. To use her hands."),
		TEXT("Open in a darkroom, red light, a print surfacing in the developer tray  -  we never quite see it, only her face watching it bloom, lit red, unreadable. She lifts it dripping, looks at it the way you look at a wound, and pins it to a windshield already papered with copies. She climbs into the car. The flashbulb rig pops once, blinding the frame to white. Title card: THE PHOTOGRAPHER."),
		TEXT("She wins. The Auditor hands her a camera  -  hers, the one. 'The entry has been struck.' She is back in the quarter-second, lens up, light perfect, finger on the shutter. And this time she puts the camera down. She uses her hands. She gathers the child up and runs  -  and the ending refuses her even the certainty of whether the child lives, because the frame goes with her instead of staying, and the photograph is never taken. The image that shamed governments into moving, the one that fed a hundred thousand because two hundred million people could not look away, never exists. She saved the one child in her hands and un-saved the ones the picture would have reached. She never knows this. She only knows she dropped the camera and held a child, and she is at peace, finally, for the first time in twenty years. The horror is ours, not hers: the Auditor lets her keep her peace, and shows the audience the count. 'You wished to use your hands. You had two. The photograph had millions. I balanced it.' Final shot: Mona, old and serene, in a sunny room with no photographs on the walls, having traded the worst thing she ever did  -  which was also, exactly, the best  -  for a clean conscience she did not earn and will never question. Cut to black."),
		false
	},
	{
		TEXT("Vault"), TEXT("16"), TEXT("VAULT"),
		TEXT("There is no wish I want granted. I came to close the Ledger."),
		TEXT("Vault is unlocked after completing all fifteen standard endings. His backstory is revealed across the campaign through hidden audio logs.\n\nVault was once a contestant in the previous Black Ledger tournament, ten years prior. He won. He made his wish. He learned what we have learned  -  that wishes are debts and the Ledger always balances. His wish, whatever it was, destroyed his life. But unlike the others, he did not accept it. He spent the next ten years studying the Auditor  -  finding the previous tournaments (every decade for centuries), finding the previous winners (all of whom died young, broken). He learned that the Auditor is not a person but a process. He learned the rules.\n\nHe has returned to compete again. He is the only contestant who cannot be granted a wish  -  he has already had his  -  and so he cannot be undone. He is here to close the Ledger permanently.\n\nHis face is never shown. We never learn his real name. The official record of the previous tournament's winner does not exist; the Auditor erased him from history as part of his wish."),
		TEXT("Vault has no intro cinematic. He simply appears on the roster after the fifteenth ending. Selecting him plays a montage of cryptic images: a different tournament, in a different decade. A different city, equally dying. A man in a charcoal suit. A figure in black walking away from a burning building, then climbing into the armored car. Title card: VAULT."),
		TEXT("Vault wins the tournament. The Auditor sits across from him. 'You knew the cost. You knew you could not be paid.' Vault speaks for the first time: 'I came to balance the Ledger.' He places his hand on the book. Pages tear themselves free  -  every contestant's page, blank now. The Auditor's form flickers. The Auditor was never a person; he was the Ledger's enforcement mechanism, and the Ledger has been closed. The flicker grows. The Auditor smiles, faintly, for the first time. 'Then I am free as well.' He dissipates. Vault stands alone in Ashen Hollow. The streetlights stop flickering. The radio stations resume normal broadcast. Vault drives out of the city. We follow Iron Page down a road lit by dawn. He does not look back. In the distance, behind him, the city is empty and at peace. Cut to credits."),
		false
	},
};

// --- Collector bosses (shown on the roster only once unlocked) ---
static const FBLVehicleBio GBLBossBios[] =
{
	{
		TEXT("Foundryman"), TEXT("B1"), TEXT("THE FOUNDRYMAN - \"TAP\""),
		TEXT("Heat doesn't forgive. It just waits for you to slow down."),
		TEXT("A contestant two tournaments ago  -  a furnace tapper at a mill in another dying city who wished to 'burn away' his debts. He lost. The Auditor read the wish literally and bound him to the heat he loved: now he is the man and the furnace both. He has forgotten his name. He remembers temperature."),
		TEXT("The Mill's center furnace lights without warning; the floor floods orange; Cupola rises through the slag like a ship surfacing. 'You're early for the pour.'"),
		TEXT("His shell goes dark; the man-shape inside finally cools, exhales decades of heat, and is gone. The Auditor signs Cupola over to you. Playable: a max-armor, near-immovable juggernaut whose special, 'Tap the Heat,' lays a budget-breaking wall of molten slag  -  like Crucible's Pour, but bigger and hotter. The slowest, hardest-to-kill thing in the game."),
		true
	},
};

